### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by agronick** [norly/elmcan#1]
I'm trying to connect via bluetooth. After I run `ldattach` on the bluetooth device I've connected with `rfcomm` I get a `can0` network device. I try doing `ip link set can0  bitrate 38400` but it won't let me set it that low. I have to do something like `ip link set can0 up type can bitrate 125000`. I can then bring the device up but candump shows nothing. My end goal is to connect it to something like Kayak. Any idea how this would be done. Am I on the right path?

**Comment by agronick** [comment]
Edit: `socketcand -i can0` got it in Kyak but theres no data.

**Comment by norly** [comment]
Hi, sorry I only spotted this just now.

> `ip link set can0 bitrate 38400`

This seems like you're trying to set a RS232 baudrate as the CAN bus speed. You need to configure the RS232 baudrate first before running ldattach. But wait, you're using rfcomm - does that even care about baudrates?

In theory, you should be able to run rfcomm, and then:
`sudo ldattach \
       --debug \
       --speed 38400 \
       --eightbits \
       --noparity \
       --onestopbit \
       --iflag -ICRNL,INLCR,-IXOFF \
       29 \
       /dev/rfcommX
`

After that, proceed as usual, if in doubt take the CAN interface down first:
`sudo ip link set can0 down`
`sudo ip link set can0 type can bitrate 125000`
`sudo ip link set can0 type can listen-only off`
`sudo ip link set can0 up`

Make sure your baud rate is correct for your target bus. Make sure the termination is correct - some adapters may have terminating resitors that need to be removed if you're hooking into an existing bus (see README). Also check `dmesg` - your adapter may be acting up like mine did. In this case, load the module with `sudo insmod elmcan.ko accept_flaky_uart=1` (see README as well).

Let me know how you're getting on!

**Comment by agronick** [comment]
Thanks for reaching back out. I shattered my leg and won't be even getting into my car for some time. I'll give this a try when I can drive again.

**Comment by marcioakyama** [comment]
Hi! I followed all instructions, and when I try to run any commands from can-utils, it does not bring anything.

after I run `./attach-me.sh /dev/ttyUSB0` it shows 

ldattach: iflag (set/clear): 64/4352
ldattach: opened /dev/ttyUSB1
ldattach: set to raw 38400 8n1: cflag=0xcbf
ldattach: line discipline set to 29

then I proceed with 

`sudo ip link set can0 down
sudo ip link set can0 type can bitrate 125000
sudo ip link set can0 type can listen-only off
sudo ip link set can0 up`

when I try to get something from the can using `cansniffer can0` or `candump can0` it does not return anything

Am I doing something wrong?

**Comment by marcioakyama** [comment]
When I open with cuteCom, I send ATMA it returns some lines of hex data and finish with buffer full

**Comment by norly** [comment]
Glad to hear you're feeling better!

What you did sounds right. Since you can see data with `ATMA` there shouldn't be an issue with CAN termination resistors.
Please check elmcan's output in dmesg and report back. You can also try loading the module with the parameter `accept_flaky_uart=1`.

**Comment by marcioakyama** [comment]
Hi that's what I got on dmesg

[55773.843972] can0: elmcan on ttyUSB0.
[56080.031323] IPv6: ADDRCONF(NETDEV_CHANGE): can0: link becomes ready
[56080.035020] can0: Received illegal character 0a.
[56080.035044] can0: ELM327 misbehaved. Blocking further communication.
[56080.035046] can0: bus-off

**Comment by norly** [comment]
Yup, you need to try `accept_flaky_uart=1`.

**Comment by marcioakyama** [comment]
it worked fine! thanks!

**Comment by norly** [comment]
I'm glad to hear. Enjoy!

Also, since this driver seems to be picking up in popularity, I'm curious to know what everyone is using this driver for. I'd appreciate your story :)

**Comment by norly** [comment]
Oh, since you mentioned `BUFFER FULL` when running `ATMA`:
It seems like I haven't mentioned this in the documentation, but what the driver does is essentially requesting `ATMA` again and again, every time it errors out due to the ELM327's RS232 TX buffer overflowing. This means that depending on CAN bus load, you'll be missing out on quite a bit of CAN data. That's yet another one of the ELM327's limitations. Increasing the RS232 speed would improve, but never fully fix this. You can try reconfiguring your ELM327 for higher RS232 speeds, and then adapting the baud rate in the ldattach call accordingly. I've never tried this myself though.

**Comment by marcioakyama** [comment]
How can I reconfiguring the speed? I will write an article in portuguese explaining how to use this driver, I'm sure it will help a lot

**Comment by norly** [comment]
You can reconfigure the speed using the commands described in the ELM327 documentation.
I've designed the driver such that it will *keep* the UART baud rate once you've set it (i.e. it uses `AT WS` to reset the ELM327, rather than `AT Z`). So it should be possible to issue `AT BRD divisor`, after which the ELM327 will change to the new RS232 speed, and then ldattach with the new speed.

Thanks for writing the article, that's a great idea! I'd appreciate a link to it once it's done :)
