### ISSUE TITLE
No messages received

### ISSUE THREAD

**Issue by 2m** [norly/elmcan#7]
Hi! I was very glad to find this project. Looking forward to using by OBDLink LX device with SavvyCAN and other socketcan software.

I have verified with ESP32 CAN reader that my car is constantly sending CAN messages with IDs `0x45A` `0x4E0` when engine is on. I also see these messages in RaceChrono Android application when using OBDLink LX.

However after setting up elmcan `candump can0` does not return any messages. How could I debug this situation?

I am able to connect to the OBDLink via `picocom` and the ELM version is `ELM327 v1.4b`. `ldattach` runs fine and `can0` device is created. However neither `candump` and neither `cansniffer` is showing CAN messages on the bus.

**Comment by norly** [comment]
After `ldattach`, the `can0` interface starts out offline and unconfigured. Could you please share how you set it up before you start `candump can0`?
I should add some example commands to the README, seems like I forgot to do so.

Here's how I start my interface after `ldattach` - make sure the bitrate matches your CAN bus:

    # The interface needs to be down to change parameters
    sudo ip link set can0 down
    sudo ip link set can0 type can bitrate 100000
    sudo ip link set can0 up

Does this solve your issue?

**Comment by 2m** [comment]
Yup, I used these commands in my experiments. Also tried different
bitrates: 500k, 250k, 125k.

**Comment by norly** [comment]
You need to set the exact bitrate that your car uses, otherwise you'll see nothing at all. Your ESP32 solution should confirm the bitrate.

How about bus termination? There's a note about this in the README. If you connect the ESP32 based device to your car and communication works, does that keep working when the ELM327 is *added* to this bus?

If nothing works, then I guess it's time for an oscilloscope and/or a "real" CAN interface :(

Also, the obligatory "is it plugged in" question: If you connect the ELM327 to the OBD port and use it as the OBD adapter it's meant to be, does that work at all?

**Comment by 2m** [comment]
Seems that I did not try 500k bitrate initially. After finding out that 500k is the default one for esp32_can (https://github.com/collin80/can_common/blob/07605a2a9f4963ee68a9ecf7790d38b22f6d2cdf/src/can_common.h#L29) I tried it again, and now I can see these messages in `candump` and `cansniffer`. Awesome! :)

**Comment by norly** [comment]
I'm glad you figured it out, thanks for the feedback and enjoy your new CAN toy! :)
